import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: ["installation", "usage"],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/branch-key",
        "guides/agents",
        "guides/configuration",
        "guides/formatting",
        "guides/environment",
        "guides/exit-codes",
      ],
    },
    // Command reference is generated from the CLI by scripts/gen_cli_docs.py;
    // its category label/order come from the _category_.json files it writes.
    { type: "autogenerated", dirName: "reference" },
    "contributing",
  ],
};

export default sidebars;
